language: node_js
node_js:
  - 10.17.0
install: npm ci
script: 
  - npm run lint:all
  - npm run test:all
  - npm run build:all
before_deploy:
  - rm -rf node_modules
  - zip -r --exclude=\*.git\* app.zip .
after_deploy:
  - rm app.zip
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-east-1"
  app: "setlister"
  env: "Setlister-env"
  bucket_name: "elasticbeanstalk-us-east-1-132412502229"
  zip-file: app.zip
  skip_cleanup: true
