language: node_js
node_js:
  - 10.14.1
install: npm ci
script: 
  - npm run lint 
  - npm run test 
  - npm run build:all
before_deploy:
  - rm -rf node_modules
  - zip -r --exclude=\*.git app.zip
after_deploy:
  - rm app.zip
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAR5VDGODKUSJ6PBF7"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "setlister"
  env: "Setlister-env"
  zip-file: app.zip
  skip_cleanup: true
